#!/bin/bash

# Exit if any error occurs
set -e

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install libusb-1.0-0-dev
sudo apt-get install libssl-dev

if [[ ! -d /home/administrator/catkin_ws/src/librealsense ]];
then
	mkdir /home/administrator/catkin_ws
	mkdir /home/administrator/catkin_ws/src
	cd /home/administrator/catkin_ws/src
	catkin_init_workspace
	git clone https://github.com/IntelRealSense/librealsense.git
	cd librealsense
else
	cd /home/administrator/catkin_ws/src/librealsense
	git pull
fi

./scripts/install_glfw3.sh
./scripts/install_dependencies-4.4.sh
./scripts/patch-uvcvideo-4.4.sh v4.4-wily

sudo cp config/99-realsense-libusb.rules /etc/udev/rules.d/
sudo udevadm control --reload-rules && udevadm trigger

make && sudo make install

sudo cp -r /home/administrator/catkin_ws/src/librealsense/include/librealsense /usr/local/include

if [[ ! -d /home/administrator/catkin_ws/src/realsense ]];
then
	cd /home/administrator/catkin_ws/src
	git clone https://github.com/intel-ros/realsense.git
else
	cd /home/administrator/catkin_ws/src/realsense
	git pull
fi

cd /home/administrator/catkin_ws
catkin_make
