#!/bin/bash

# Exit if any error occurs
set -e

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install libusb-1.0-0-dev
sudo apt-get install libssl-dev

if [[ ! -d /home/$USER/catkin_ws/src/librealsense ]];
then
	mkdir /home/$USER/catkin_ws
	mkdir /home/$USER/catkin_ws/src
	cd /home/$USER/catkin_ws/src
	catkin_init_workspace
	git clone https://github.com/IntelRealSense/librealsense.git
	cd librealsense

	./scripts/install_glfw3.sh
	./scripts/install_dependencies-4.4.sh
	./scripts/patch-uvcvideo-4.4.sh v4.4-wily

	sudo cp config/99-realsense-libusb.rules /etc/udev/rules.d/
	sudo udevadm control --reload-rules && udevadm trigger

	cd /home/$USER/catkin_ws/src/librealsense

	make && sudo make install

	sudo cp -r /home/$USER/catkin_ws/src/librealsense/include/librealsense /usr/local/include
else
	exit 1
fi

if [[ ! -d /home/$USER/catkin_ws/src/realsense ]];
then
	cd /home/$USER/catkin_ws/src
	git clone https://github.com/intel-ros/realsense.git
fi

cd /home/$USER/catkin_ws
catkin_make
